
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
spec:
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.servicePort }}
  type: LoadBalancer
